repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v1.1.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        files: ^git-phab$
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: flake8
        files: .*\.py$\|bin/pitivi.in
-   repo: https://github.com/pre-commit/pre-commit.git
    sha: v1.4.5
    hooks:
    -   id: validate_manifest
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v1.0.1
    hooks:
    -   id: reorder-python-imports
