# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_VideoPlayerDialog.ui'
#
# Created: Fri Apr 16 19:59:26 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_VideoPlayerDialog(object):
    def setupUi(self, VideoPlayerDialog):
        VideoPlayerDialog.setObjectName("VideoPlayerDialog")
        VideoPlayerDialog.resize(520, 465)
        VideoPlayerDialog.setMaximumSize(QtCore.QSize(600, 500))
        self.centralwidget = QtGui.QWidget(VideoPlayerDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.fileLineEdit = QtGui.QLineEdit(self.centralwidget)
        self.fileLineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 111, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 223, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.fileLineEdit.setPalette(palette)
        self.fileLineEdit.setAutoFillBackground(True)
        self.fileLineEdit.setReadOnly(True)
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.horizontalLayout_3.addWidget(self.fileLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.videoPlayer = phonon.Phonon.VideoPlayer(self.centralwidget)
        self.videoPlayer.setMinimumSize(QtCore.QSize(500, 300))
        self.videoPlayer.setObjectName("videoPlayer")
        self.verticalLayout.addWidget(self.videoPlayer)
        self.seekSlider = phonon.Phonon.SeekSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seekSlider.sizePolicy().hasHeightForWidth())
        self.seekSlider.setSizePolicy(sizePolicy)
        self.seekSlider.setMinimumSize(QtCore.QSize(300, 21))
        self.seekSlider.setObjectName("seekSlider")
        self.verticalLayout.addWidget(self.seekSlider)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playToolButton = QtGui.QToolButton(self.centralwidget)
        self.playToolButton.setMinimumSize(QtCore.QSize(40, 40))
        self.playToolButton.setAutoFillBackground(True)
        self.playToolButton.setAutoRaise(False)
        self.playToolButton.setObjectName("playToolButton")
        self.horizontalLayout.addWidget(self.playToolButton)
        self.pauseToolButton = QtGui.QToolButton(self.centralwidget)
        self.pauseToolButton.setMinimumSize(QtCore.QSize(40, 40))
        self.pauseToolButton.setAutoRaise(False)
        self.pauseToolButton.setObjectName("pauseToolButton")
        self.horizontalLayout.addWidget(self.pauseToolButton)
        self.stopToolButton = QtGui.QToolButton(self.centralwidget)
        self.stopToolButton.setMinimumSize(QtCore.QSize(40, 40))
        self.stopToolButton.setAutoRaise(False)
        self.stopToolButton.setObjectName("stopToolButton")
        self.horizontalLayout.addWidget(self.stopToolButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.centralwidget)
        self.volumeSlider.setMinimumSize(QtCore.QSize(110, 22))
        self.volumeSlider.setMaximumSize(QtCore.QSize(110, 22))
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_2.addWidget(self.volumeSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        VideoPlayerDialog.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(VideoPlayerDialog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        VideoPlayerDialog.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(VideoPlayerDialog)
        self.statusbar.setObjectName("statusbar")
        VideoPlayerDialog.setStatusBar(self.statusbar)
        self.fileOpenAction = QtGui.QAction(VideoPlayerDialog)
        self.fileOpenAction.setObjectName("fileOpenAction")
        self.fileExitAction = QtGui.QAction(VideoPlayerDialog)
        self.fileExitAction.setObjectName("fileExitAction")
        self.fullScreenAction = QtGui.QAction(VideoPlayerDialog)
        self.fullScreenAction.setCheckable(True)
        self.fullScreenAction.setObjectName("fullScreenAction")
        self.menuFile.addAction(self.fileOpenAction)
        self.menuFile.addAction(self.fileExitAction)
        self.menuView.addAction(self.fullScreenAction)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(VideoPlayerDialog)
        QtCore.QMetaObject.connectSlotsByName(VideoPlayerDialog)

    def retranslateUi(self, VideoPlayerDialog):
        VideoPlayerDialog.setWindowTitle(QtGui.QApplication.translate("VideoPlayerDialog", "Video Player", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("VideoPlayerDialog", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.playToolButton.setText(QtGui.QApplication.translate("VideoPlayerDialog", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseToolButton.setText(QtGui.QApplication.translate("VideoPlayerDialog", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.stopToolButton.setText(QtGui.QApplication.translate("VideoPlayerDialog", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("VideoPlayerDialog", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("VideoPlayerDialog", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setText(QtGui.QApplication.translate("VideoPlayerDialog", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.fileExitAction.setText(QtGui.QApplication.translate("VideoPlayerDialog", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.fullScreenAction.setText(QtGui.QApplication.translate("VideoPlayerDialog", "Full Screen", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import phonon
