# -*- coding: utf-8 -*-
# # @license: This program is free software: you can redistribute it and/or modify
#           it under the terms of the GNU General Public License as published by
#           the Free Software Foundation, either version 3 of the License, or
#           (at your option) any later version.
#
#           This program is distributed in the hope that it will be useful,
#           but WITHOUT ANY WARRANTY; without even the implied warranty of
#           MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#           GNU General Public License for more details.
#
#           You should have received a copy of the GNU General Public License
#           along with this program.  If not, see <http://www.gnu.org/licenses/>.
# @see: ThumbnailMakerDialog.py
# Form implementation generated from reading ui file 'thumbnailMaker.ui'
#
# Created: Mon Dec 21 15:11:47 2009
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ThumbnailMakerDialog(object):
    def setupUi(self, ThumbnailMakerDialog):
        ThumbnailMakerDialog.setObjectName("ThumbnailMakerDialog")
        ThumbnailMakerDialog.resize(550, 305)
        ThumbnailMakerDialog.setMaximumSize(QtCore.QSize(550, 400))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(194, 168, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        ThumbnailMakerDialog.setPalette(palette)
        ThumbnailMakerDialog.setAutoFillBackground(True)
        self.gridLayout = QtGui.QGridLayout(ThumbnailMakerDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtGui.QLineEdit(ThumbnailMakerDialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 223, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.lineEdit.setPalette(palette)
        self.lineEdit.setAutoFillBackground(True)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputFileLabel = QtGui.QLabel(ThumbnailMakerDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputFileLabel.sizePolicy().hasHeightForWidth())
        self.inputFileLabel.setSizePolicy(sizePolicy)
        self.inputFileLabel.setObjectName("inputFileLabel")
        self.horizontalLayout.addWidget(self.inputFileLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.inputLineEdit = QtGui.QLineEdit(ThumbnailMakerDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputLineEdit.sizePolicy().hasHeightForWidth())
        self.inputLineEdit.setSizePolicy(sizePolicy)
        self.inputLineEdit.setMaximumSize(QtCore.QSize(120, 20))
        self.inputLineEdit.setObjectName("inputLineEdit")
        self.horizontalLayout.addWidget(self.inputLineEdit)
        self.inputFileDialogButton = QtGui.QPushButton(ThumbnailMakerDialog)
        self.inputFileDialogButton.setMinimumSize(QtCore.QSize(20, 20))
        self.inputFileDialogButton.setMaximumSize(QtCore.QSize(20, 20))
        self.inputFileDialogButton.setObjectName("inputFileDialogButton")
        self.horizontalLayout.addWidget(self.inputFileDialogButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outputLocationLabel = QtGui.QLabel(ThumbnailMakerDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputLocationLabel.sizePolicy().hasHeightForWidth())
        self.outputLocationLabel.setSizePolicy(sizePolicy)
        self.outputLocationLabel.setObjectName("outputLocationLabel")
        self.horizontalLayout_2.addWidget(self.outputLocationLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.outputLineEdit = QtGui.QLineEdit(ThumbnailMakerDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputLineEdit.sizePolicy().hasHeightForWidth())
        self.outputLineEdit.setSizePolicy(sizePolicy)
        self.outputLineEdit.setMaximumSize(QtCore.QSize(120, 20))
        self.outputLineEdit.setObjectName("outputLineEdit")
        self.horizontalLayout_2.addWidget(self.outputLineEdit)
        self.outputLocationDialogButton = QtGui.QPushButton(ThumbnailMakerDialog)
        self.outputLocationDialogButton.setMinimumSize(QtCore.QSize(20, 20))
        self.outputLocationDialogButton.setMaximumSize(QtCore.QSize(20, 20))
        self.outputLocationDialogButton.setObjectName("outputLocationDialogButton")
        self.horizontalLayout_2.addWidget(self.outputLocationDialogButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.fileFormatLabel = QtGui.QLabel(ThumbnailMakerDialog)
        self.fileFormatLabel.setObjectName("fileFormatLabel")
        self.horizontalLayout_4.addWidget(self.fileFormatLabel)
        spacerItem2 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.fileFormatComboBox = QtGui.QComboBox(ThumbnailMakerDialog)
        self.fileFormatComboBox.setObjectName("fileFormatComboBox")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.fileFormatComboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.fileFormatComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.imageFiltersLabel = QtGui.QLabel(ThumbnailMakerDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageFiltersLabel.sizePolicy().hasHeightForWidth())
        self.imageFiltersLabel.setSizePolicy(sizePolicy)
        self.imageFiltersLabel.setObjectName("imageFiltersLabel")
        self.horizontalLayout_5.addWidget(self.imageFiltersLabel)
        spacerItem3 = QtGui.QSpacerItem(55, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.imageFiltersComboBox = QtGui.QComboBox(ThumbnailMakerDialog)
        self.imageFiltersComboBox.setObjectName("imageFiltersComboBox")
        self.imageFiltersComboBox.addItem("")
        self.imageFiltersComboBox.addItem("")
        self.imageFiltersComboBox.addItem("")
        self.imageFiltersComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.imageFiltersComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.imageSizeLabel = QtGui.QLabel(ThumbnailMakerDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageSizeLabel.sizePolicy().hasHeightForWidth())
        self.imageSizeLabel.setSizePolicy(sizePolicy)
        self.imageSizeLabel.setObjectName("imageSizeLabel")
        self.horizontalLayout_3.addWidget(self.imageSizeLabel)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        spacerItem5 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.widthLabel = QtGui.QLabel(ThumbnailMakerDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthLabel.sizePolicy().hasHeightForWidth())
        self.widthLabel.setSizePolicy(sizePolicy)
        self.widthLabel.setObjectName("widthLabel")
        self.horizontalLayout_3.addWidget(self.widthLabel)
        self.widthLineEdit = QtGui.QLineEdit(ThumbnailMakerDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthLineEdit.sizePolicy().hasHeightForWidth())
        self.widthLineEdit.setSizePolicy(sizePolicy)
        self.widthLineEdit.setMaximumSize(QtCore.QSize(30, 20))
        self.widthLineEdit.setObjectName("widthLineEdit")
        self.horizontalLayout_3.addWidget(self.widthLineEdit)
        self.label_3 = QtGui.QLabel(ThumbnailMakerDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(35, 20))
        self.label_3.setMaximumSize(QtCore.QSize(35, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.heightLineEdit = QtGui.QLineEdit(ThumbnailMakerDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightLineEdit.sizePolicy().hasHeightForWidth())
        self.heightLineEdit.setSizePolicy(sizePolicy)
        self.heightLineEdit.setMaximumSize(QtCore.QSize(30, 20))
        self.heightLineEdit.setObjectName("heightLineEdit")
        self.horizontalLayout_3.addWidget(self.heightLineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.aspectRatioCheckBox = QtGui.QCheckBox(ThumbnailMakerDialog)
        self.aspectRatioCheckBox.setChecked(True)
        self.aspectRatioCheckBox.setObjectName("aspectRatioCheckBox")
        self.verticalLayout_2.addWidget(self.aspectRatioCheckBox)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtGui.QLabel(ThumbnailMakerDialog)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.rotationAngleSpinBox = QtGui.QSpinBox(ThumbnailMakerDialog)
        self.rotationAngleSpinBox.setMinimumSize(QtCore.QSize(44, 22))
        self.rotationAngleSpinBox.setMaximumSize(QtCore.QSize(44, 22))
        self.rotationAngleSpinBox.setMinimum(-180)
        self.rotationAngleSpinBox.setMaximum(180)
        self.rotationAngleSpinBox.setObjectName("rotationAngleSpinBox")
        self.horizontalLayout_7.addWidget(self.rotationAngleSpinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(ThumbnailMakerDialog)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.graphicsView = QtGui.QGraphicsView(ThumbnailMakerDialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(260, 220))
        self.graphicsView.setMaximumSize(QtCore.QSize(500, 500))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.okPushButton = QtGui.QPushButton(ThumbnailMakerDialog)
        self.okPushButton.setMinimumSize(QtCore.QSize(50, 30))
        self.okPushButton.setMaximumSize(QtCore.QSize(50, 30))
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout_6.addWidget(self.okPushButton)
        self.closePushButton = QtGui.QPushButton(ThumbnailMakerDialog)
        self.closePushButton.setMinimumSize(QtCore.QSize(50, 30))
        self.closePushButton.setMaximumSize(QtCore.QSize(50, 30))
        self.closePushButton.setObjectName("closePushButton")
        self.horizontalLayout_6.addWidget(self.closePushButton)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.gridLayout.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)

        self.retranslateUi(ThumbnailMakerDialog)
        QtCore.QMetaObject.connectSlotsByName(ThumbnailMakerDialog)
        ThumbnailMakerDialog.setTabOrder(self.inputLineEdit, self.inputFileDialogButton)
        ThumbnailMakerDialog.setTabOrder(self.inputFileDialogButton, self.outputLineEdit)
        ThumbnailMakerDialog.setTabOrder(self.outputLineEdit, self.outputLocationDialogButton)
        ThumbnailMakerDialog.setTabOrder(self.outputLocationDialogButton, self.widthLineEdit)
        ThumbnailMakerDialog.setTabOrder(self.widthLineEdit, self.heightLineEdit)

    def retranslateUi(self, ThumbnailMakerDialog):
        ThumbnailMakerDialog.setWindowTitle(QtGui.QApplication.translate("ThumbnailMakerDialog", "Thumbnail Maker", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "Specify the parameters below and click OK", None, QtGui.QApplication.UnicodeUTF8))
        self.inputFileLabel.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "Input File:", None, QtGui.QApplication.UnicodeUTF8))
        self.inputFileDialogButton.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.outputLocationLabel.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "Output Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.outputLocationDialogButton.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.fileFormatLabel.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "Output File Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.fileFormatComboBox.setItemText(0, QtGui.QApplication.translate("ThumbnailMakerDialog", ".jpeg", None, QtGui.QApplication.UnicodeUTF8))
        self.fileFormatComboBox.setItemText(1, QtGui.QApplication.translate("ThumbnailMakerDialog", ".png", None, QtGui.QApplication.UnicodeUTF8))
        self.fileFormatComboBox.setItemText(2, QtGui.QApplication.translate("ThumbnailMakerDialog", ".jpg", None, QtGui.QApplication.UnicodeUTF8))
        self.fileFormatComboBox.setItemText(3, QtGui.QApplication.translate("ThumbnailMakerDialog", ".bmp", None, QtGui.QApplication.UnicodeUTF8))
        self.imageFiltersLabel.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "Resampling Filters:", None, QtGui.QApplication.UnicodeUTF8))
        self.imageFiltersComboBox.setItemText(0, QtGui.QApplication.translate("ThumbnailMakerDialog", "Antialias", None, QtGui.QApplication.UnicodeUTF8))
        self.imageFiltersComboBox.setItemText(1, QtGui.QApplication.translate("ThumbnailMakerDialog", "Bicubic", None, QtGui.QApplication.UnicodeUTF8))
        self.imageFiltersComboBox.setItemText(2, QtGui.QApplication.translate("ThumbnailMakerDialog", "Bilinear", None, QtGui.QApplication.UnicodeUTF8))
        self.imageFiltersComboBox.setItemText(3, QtGui.QApplication.translate("ThumbnailMakerDialog", "Nearest", None, QtGui.QApplication.UnicodeUTF8))
        self.imageSizeLabel.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "Image Size (pixels):", None, QtGui.QApplication.UnicodeUTF8))
        self.widthLabel.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.aspectRatioCheckBox.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "Maintain Aspect Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "Rotatation Angle (degrees):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "Output Image", None, QtGui.QApplication.UnicodeUTF8))
        self.okPushButton.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.closePushButton.setText(QtGui.QApplication.translate("ThumbnailMakerDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

