BROKER_URL = 'amqp://kemal:123456@192.168.1.21:5672/videowall'
CELERY_RESULT_BACKEND = 'amqp'

# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_ACCEPT_CONTENT=['json']
# CELERY_TIMEZONE = 'Europe/Oslo'
# CELERY_ENABLE_UTC = True