# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AudioPlayerDialog.ui'
#
# Created: Fri Apr 16 19:58:55 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AudioPlayerDialog(object):
    def setupUi(self, AudioPlayerDialog):
        AudioPlayerDialog.setObjectName("AudioPlayerDialog")
        AudioPlayerDialog.resize(320, 156)
        AudioPlayerDialog.setMinimumSize(QtCore.QSize(310, 150))
        AudioPlayerDialog.setMaximumSize(QtCore.QSize(320, 157))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 107, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 107, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 107, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(107, 107, 159))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        AudioPlayerDialog.setPalette(palette)
        AudioPlayerDialog.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(AudioPlayerDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.fileLineEdit = QtGui.QLineEdit(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 111, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(224, 223, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.fileLineEdit.setPalette(palette)
        self.fileLineEdit.setAutoFillBackground(True)
        self.fileLineEdit.setReadOnly(True)
        self.fileLineEdit.setObjectName("fileLineEdit")
        self.horizontalLayout_3.addWidget(self.fileLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.seekSlider = phonon.Phonon.SeekSlider(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seekSlider.sizePolicy().hasHeightForWidth())
        self.seekSlider.setSizePolicy(sizePolicy)
        self.seekSlider.setMinimumSize(QtCore.QSize(300, 21))
        self.seekSlider.setObjectName("seekSlider")
        self.verticalLayout.addWidget(self.seekSlider)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playToolButton = QtGui.QToolButton(self.centralwidget)
        self.playToolButton.setMinimumSize(QtCore.QSize(40, 40))
        self.playToolButton.setAutoFillBackground(True)
        self.playToolButton.setAutoRaise(False)
        self.playToolButton.setObjectName("playToolButton")
        self.horizontalLayout.addWidget(self.playToolButton)
        self.pauseToolButton = QtGui.QToolButton(self.centralwidget)
        self.pauseToolButton.setMinimumSize(QtCore.QSize(40, 40))
        self.pauseToolButton.setAutoRaise(False)
        self.pauseToolButton.setObjectName("pauseToolButton")
        self.horizontalLayout.addWidget(self.pauseToolButton)
        self.stopToolButton = QtGui.QToolButton(self.centralwidget)
        self.stopToolButton.setMinimumSize(QtCore.QSize(40, 40))
        self.stopToolButton.setAutoRaise(False)
        self.stopToolButton.setObjectName("stopToolButton")
        self.horizontalLayout.addWidget(self.stopToolButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.centralwidget)
        self.volumeSlider.setMinimumSize(QtCore.QSize(110, 22))
        self.volumeSlider.setMaximumSize(QtCore.QSize(110, 22))
        self.volumeSlider.setObjectName("volumeSlider")
        self.horizontalLayout_2.addWidget(self.volumeSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        AudioPlayerDialog.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(AudioPlayerDialog)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAudioEffects = QtGui.QMenu(self.menubar)
        self.menuAudioEffects.setObjectName("menuAudioEffects")
        AudioPlayerDialog.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(AudioPlayerDialog)
        self.statusbar.setObjectName("statusbar")
        AudioPlayerDialog.setStatusBar(self.statusbar)
        self.fileOpenAction = QtGui.QAction(AudioPlayerDialog)
        self.fileOpenAction.setObjectName("fileOpenAction")
        self.fileExitAction = QtGui.QAction(AudioPlayerDialog)
        self.fileExitAction.setObjectName("fileExitAction")
        self.menuFile.addAction(self.fileOpenAction)
        self.menuFile.addAction(self.fileExitAction)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAudioEffects.menuAction())

        self.retranslateUi(AudioPlayerDialog)
        QtCore.QMetaObject.connectSlotsByName(AudioPlayerDialog)

    def retranslateUi(self, AudioPlayerDialog):
        AudioPlayerDialog.setWindowTitle(QtGui.QApplication.translate("AudioPlayerDialog", "Audio Player", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AudioPlayerDialog", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.playToolButton.setText(QtGui.QApplication.translate("AudioPlayerDialog", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.pauseToolButton.setText(QtGui.QApplication.translate("AudioPlayerDialog", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.stopToolButton.setText(QtGui.QApplication.translate("AudioPlayerDialog", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("AudioPlayerDialog", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAudioEffects.setTitle(QtGui.QApplication.translate("AudioPlayerDialog", "Effects", None, QtGui.QApplication.UnicodeUTF8))
        self.fileOpenAction.setText(QtGui.QApplication.translate("AudioPlayerDialog", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.fileExitAction.setText(QtGui.QApplication.translate("AudioPlayerDialog", "Exit", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import phonon
